mystr = "This is learning day"
print(mystr[0:20])
print(len(mystr))
print(mystr[0:20:2])
print(mystr[-4:-2])
print(mystr.isalnum())
print(mystr.endswith("day"))
print(mystr.count("i"))
print(mystr.find("is"))
print(mystr.capitalize())
print(mystr.upper())
print(mystr.replace("is", "are"))